localization fix
GoodsPartner/GoodsPartner pull request #1126
Opened 2023-10-06 14:06 UTC by Clio18

- create context and put there calling useTranslation() hook
- change calling useTranslation() hook to using it result from the context in each component

2023-10-06 14:57 UTC, radeon323 requested changes

2023-10-06 14:57 UTC, radeon323 commented on goods-partner-frontend/src/pages/Cars/CarFormDialog/CarFormDialog.tsx
> +	// const { t } = useContext(LanguageContext);
delete this one

2023-10-06 14:57 UTC, radeon323 commented on goods-partner-frontend/src/components/ConfirmationDialog/ConfirmationDialog.tsx
> +	// const { t } = useContext(LanguageContext);
delete this one

2023-10-06 14:57 UTC, radeon323 commented on goods-partner-frontend/src/pages/Delivery/DeliveryRoutes/RouteContent/RoutePointDetails/RoutePointDetailsBody/RoutePointDetailsBody.tsx
> +	//const { t } = useContext(LanguageContext);
delete this one

2023-10-06 14:57 UTC, radeon323 commented on goods-partner-frontend/src/pages/Delivery/DeliveryRoutes/RouteContent/RoutePointDetails/RoutePointDetailsHeader/RoutePointDetailsHeader.tsx
> +	// const { t } = useContext(LanguageContext);
delete this one

2023-10-07 13:59 UTC, Clio18 commented on goods-partner-frontend/src/pages/Delivery/DeliveryRoutes/RouteContent/RoutePointDetails/RoutePointDetailsBody/RoutePointDetailsBody.tsx
> +	//const { t } = useContext(LanguageContext);
Done

2023-10-07 13:59 UTC, Clio18 commented on goods-partner-frontend/src/pages/Delivery/DeliveryRoutes/RouteContent/RoutePointDetails/RoutePointDetailsHeader/RoutePointDetailsHeader.tsx
> +	// const { t } = useContext(LanguageContext);
Done

2023-10-07 13:59 UTC, Clio18 commented on goods-partner-frontend/src/components/ConfirmationDialog/ConfirmationDialog.tsx
> +	// const { t } = useContext(LanguageContext);
Done

2023-10-07 13:59 UTC, Clio18 commented on goods-partner-frontend/src/pages/Cars/CarFormDialog/CarFormDialog.tsx
> +	// const { t } = useContext(LanguageContext);
Done

2023-10-07 21:52 UTC, merged