added tokens repository
GoodsPartner/GoodsPartner pull request #1137
Opened 2023-10-11 17:38 UTC by GuchiTheHasky

Added storage of the refresh tokens in the database.

2023-11-17 08:19 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/entity/Token.java
> +    private Set<RefreshToken> refreshTokens = new HashSet<>();
I dont understand why we need a set here

2023-11-20 18:20 UTC, 0ffffh requested changes

2023-11-20 18:20 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/repository/TokenRepository.java
> +    private final JdbcTemplate jdbcTemplate;
why you use here JdbcTemplate ?

2023-11-20 18:20 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/repository/TokenRepository.java
> +        return jdbcTemplate.queryForList("SELECT * FROM refresh_tokens", String.class);
* Try to always request only what is necessary

2023-11-20 18:20 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/SecurityService.java
> +    void logout(String refreshToken);
I guess here we should pass username (or email) to remove all tokens relies to user

2023-11-20 18:20 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/TokenService.java
> +
From http://static.springsource.org/spring/docs/2.0.x/reference/transaction.html

`    The Spring team's recommendation is that you only annotate concrete classes with the @Transactional annotation, as opposed to annotating interfaces.`

2023-11-20 18:20 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/impl/DefaultJwtService.java
> +        }
claims.getExpiration() return java.util.Date. more convenient way, to use special methods of Date class: before(), after() ..

2023-11-20 18:20 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/impl/DefaultSecurityService.java
solid - the Dependency Inversion principle states that our classes should depend upon interfaces or abstract classes instead of concrete classes.

2023-11-20 18:20 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/impl/DefaultSecurityService.java
maybe we need something like save or update ? how will you evict expired tokens from the db

2023-11-20 18:20 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/impl/DefaultSecurityService.java
> +        }
jwtService.authenticateRefreshToken(refreshJwtToken) already involves expiration checking

2023-11-20 18:20 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/AuthenticationController.java
>          logoutHandler.logout(request, response, null);
i guess be better move this logic to security service

2023-11-20 18:20 UTC, 0ffffh commented on goods-partner-backend/src/main/resources/application.yml
> +    active: ${SPRING_PROFILES_ACTIVE:dev}
do no change app.yml without reason

2023-11-20 18:20 UTC, 0ffffh commented on goods-partner-backend/src/test/java/com/goodspartner/service/security/impl/DefaultTokenServiceTest.java
> +class DefaultTokenServiceTest {
maven build fails :

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine suitable jdbc url`
```

extend AbstracTest class

2023-11-20 18:28 UTC, GuchiTheHasky commented on goods-partner-backend/src/main/java/com/goodspartner/repository/TokenRepository.java
> +    private final JdbcTemplate jdbcTemplate;
When I have entity, I used JpaRepository but now it's gone, so I used JdbcTemplate, didn't know a better alternative.

2023-11-20 18:33 UTC, GuchiTheHasky commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/impl/DefaultSecurityService.java
Sorry, my bad.

2023-11-20 18:35 UTC, GuchiTheHasky commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/AuthenticationController.java
>          logoutHandler.logout(request, response, null);
Ok.

2023-11-20 18:36 UTC, GuchiTheHasky commented on goods-partner-backend/src/test/java/com/goodspartner/service/security/impl/DefaultTokenServiceTest.java
> +class DefaultTokenServiceTest {
Ok.

2023-11-20 18:37 UTC, GuchiTheHasky commented on goods-partner-backend/src/main/resources/application.yml
> +    active: ${SPRING_PROFILES_ACTIVE:dev}
Ok.

2023-11-20 18:40 UTC, GuchiTheHasky commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/impl/DefaultSecurityService.java
I was just deleting them, but will think about the update method

2023-11-20 18:40 UTC, GuchiTheHasky commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/impl/DefaultJwtService.java
> +        }
Ok, thanks.)

2023-11-20 18:42 UTC, GuchiTheHasky commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/TokenService.java
> +
Ok.

2023-11-20 18:51 UTC, GuchiTheHasky commented on goods-partner-backend/src/main/java/com/goodspartner/repository/TokenRepository.java
> +        return jdbcTemplate.queryForList("SELECT * FROM refresh_tokens", String.class);
We have only one column in refresh_tokens table, but thanks I will fix it.

2023-11-20 21:06 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/impl/DefaultTokenService.java
> +
what if findAll return one million records? I guess you need add some timestamp field to db or something like this, and limit cache size.
look about LRU/LFU cache

2023-11-20 22:28 UTC, GuchiTheHasky commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/impl/DefaultTokenService.java
> +
Ok, thanks.)

2023-11-20 23:24 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/SecurityService.java
> +    void logout(String refreshToken);
if we keep it this way, we will logout user only from one device, which is also ok. 
its a trade of

2023-11-20 23:25 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/impl/DefaultJwtService.java
> +        }
+

2023-11-20 23:25 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/impl/DefaultSecurityService.java
agree

2023-11-21 08:01 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/security/impl/DefaultJwtService.java
> -            log.warn("Expired token: {} token: {}", expiredJwtException.getMessage(), token);
why we dont catch this anymore?

2023-11-21 08:07 UTC, belosh59 commented on goods-partner-backend/src/main/resources/db/migration/V1.19__Initial_token_table.sql
> +    token varchar(255)
primary key required

2023-11-23 08:52 UTC, belosh59 approved these changes

2023-11-23 08:52 UTC, merged