Complete approve route point
GoodsPartner/GoodsPartner pull request #341
Opened 2022-11-18 21:51 UTC by Ishei5

- changed RoutePointDto - excluded orders and mapPoint;
 - changed parameter type for reorderRoutePoints method to RoutePoint

2022-11-18 22:10 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/RouteController.java
> +                                   @RequestBody LinkedList<RoutePoint> routePointResponses) {
Controller accept persistence Entity?

2022-11-18 22:31 UTC, belosh59 requested changes

2022-11-18 22:31 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/RouteController.java
> +import com.goodspartner.entity.RoutePoint;
this mixing of objects should confuse you

2022-11-18 22:31 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/dto/RoutePointDto.java
> -    private MapPoint mapPoint;
here

2022-11-18 22:31 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/RouteService.java
> +    void reorderRoutePoints(int id, LinkedList<RoutePoint> routePointResponses);
This method should use DTO instead of Entity

2022-11-19 19:59 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/RouteController.java
> +                                   @RequestBody LinkedList<RoutePoint> routePointResponses) {
Rollback to Dto

2022-11-19 19:59 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/RouteController.java
> +import com.goodspartner.entity.RoutePoint;
Agree, Rollback to Dto

2022-11-19 19:59 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/service/RouteService.java
> +    RouteDto findById(int routeId);
Done

2022-11-19 19:59 UTC, Ishei5 commented on goods-partner-backend/src/main/java/com/goodspartner/service/RouteService.java
> +    void reorderRoutePoints(int id, LinkedList<RoutePoint> routePointResponses);
Rollback to Dto

2022-11-19 22:57 UTC, belosh59 approved these changes

2022-11-19 23:00 UTC, belosh59 approved these changes

2022-11-19 23:00 UTC, merged