refactor
GoodsPartner/GoodsPartner pull request #373
Opened 2022-12-01 17:46 UTC by SashkoStahovskyi

2022-12-01 22:40 UTC, belosh59 requested changes

2022-12-01 22:40 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/repository/OrderExternalRepository.java
> +            "ON o.addressExternal.status = 'UNKNOWN' AND a.status = 'UNKNOWN'")
SELECT o FROM OrderExternal o WHERE o.addressExternal.status = 'UNKNOWN'

Why not like that? you are mixing here two approaches. 
Also you have a problem that you join not by a foreign key but by the filter condition

2022-12-02 08:24 UTC, SashkoStahovskyi commented on goods-partner-backend/src/main/java/com/goodspartner/repository/OrderExternalRepository.java
> +            "ON o.addressExternal.status = 'UNKNOWN' AND a.status = 'UNKNOWN'")
@belosh59

2022-12-02 08:30 UTC, SashkoStahovskyi commented on goods-partner-backend/src/main/java/com/goodspartner/repository/OrderExternalRepository.java
> +            "ON o.addressExternal.status = 'UNKNOWN' AND a.status = 'UNKNOWN'")
investigate my failure. fixed

2022-12-02 09:08 UTC, belosh59 approved these changes

2022-12-02 09:11 UTC, merged