Settings endpoint
GoodsPartner/GoodsPartner pull request #540
Opened 2023-02-03 15:09 UTC by SerhiiTrehubenko

#254

2023-02-03 15:24 UTC, Rooman requested changes
В целом  проделна хорошая работа над не тривиальной задачей. За старания респект. 
Минусы - помарочные замечаний + серьозный проеб со статикой.

2023-02-03 15:24 UTC, Rooman commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/SettingsExternalControllerITest.java
> +    //TODO: rename method
может можно эту тудушку сразу пофиксть?

2023-02-03 15:24 UTC, Rooman commented on goods-partner-backend/src/test/resources/datasets/settings/settings-dataset.json
> +      "properties": "{\n    \"apiKey\": \"ApiKey-87987-23654asdf\",\n    \"region\": \"Kiev\",\n    \"language\": \"Ukrainian\",\n    \"boundaries\": {\n      \"north\": 50.88,\n      \"south\": 88.6
зачем в jsone \nы

2023-02-03 15:24 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultSettingsExternalService.java
> +            throw new RuntimeException(e);
В случае такой обработки ошибок лучше использовать аннотацию @SneakyThrows

2023-02-03 15:24 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/entity/SettingsExternal.java
> +    public static class GroupId implements Serializable {
что будет если убрать Serializable?

2023-02-03 15:24 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/cache/DefaultSettingsCache.java
> +    private static Map<String, Map<String, SettingsExternal>> settingsCache;
Статика - сразу реджект. Зачем он статический? Убрать.

2023-02-03 15:24 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/cache/DefaultSettingsCache.java
> +    private static Map<String, Map<String, SettingsExternal>> settingsCache;
Введение глобального состояния - очень плохая практика. 
Инстанцы не имеют значения потому что есть глобальный стейт. 
Еще и работаем с ним в многопоточной среде.

2023-02-03 15:24 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/cache/CacheInterpreter.java
> +@Component
@Service

2023-02-04 00:47 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/cache/CacheInterpreter.java
> +@Component
Why this should be a bean?

2023-02-04 00:49 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/cache/DefaultSettingsCache.java
> +        isEmptyMap();
I dont understand purpose of this method

2023-02-06 13:34 UTC, SerhiiTrehubenko commented on goods-partner-backend/src/main/java/com/goodspartner/cache/CacheInterpreter.java
> +@Component
Я вижу это как концентратор наших сеттинговых объектов, для более удобной работы с ними. Эта идея реализована по сотоянию на 06.02.2023. Вроде бы норм.

2023-02-06 13:43 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/cache/CacheInterpreter.java
> +@Component
судя по коду цей концентратор ніде не використовується.
Я не розумю як в нього мають потрапити ці проперті і хто їх має читати

2023-02-06 13:48 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/cache/DefaultSettingsCache.java
> +    protected List<SettingsExternal> findAll() {
Method call from the same bean -> Transaction will not be created.

2023-02-06 13:48 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/cache/DefaultSettingsCache.java
> +    protected List<SettingsExternal> addSettings(List<SettingsExternal> settingsExternalList) {
same here

2023-02-06 13:51 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/SettingsExternalController.java
> +    public SettingsDto addSettings(@RequestBody SettingsDto settingsDto) {
[minor] Update settings.

You are not adding nothing new - otherwise it would be POST.
You are updating existing - thats why you are using put.
Dont confuse .

2023-02-06 14:49 UTC, SerhiiTrehubenko commented on goods-partner-backend/src/main/java/com/goodspartner/util/SettingExternalDtoParser.java
> +        ObjectMapper mapper = new ObjectMapper();
> У тебя и в поле выше и локально создается обджект маппер

Исправелно.

2023-02-06 14:49 UTC, SerhiiTrehubenko commented on goods-partner-backend/src/main/java/com/goodspartner/util/SettingExternalDtoParser.java
> +            if (Objects.equals(SettingsGroup.CLIENT, group) &&
> Энумы принято сравнитьва на ==

Исправлено.

2023-02-06 14:49 UTC, SerhiiTrehubenko commented on goods-partner-backend/src/test/java/com/goodspartner/web/controller/SettingsExternalControllerITest.java
> +    //TODO: rename method
> может можно эту тудушку сразу пофиксть?

Исправлено.

2023-02-06 14:50 UTC, SerhiiTrehubenko commented on goods-partner-backend/src/test/resources/datasets/settings/settings-dataset.json
> +      "properties": "{\n    \"apiKey\": \"ApiKey-87987-23654asdf\",\n    \"region\": \"Kiev\",\n    \"language\": \"Ukrainian\",\n    \"boundaries\": {\n      \"north\": 50.88,\n      \"south\": 88.6
> зачем в jsone \nы

Исправлено.

2023-02-06 14:50 UTC, SerhiiTrehubenko commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultSettingsExternalService.java
> +            throw new RuntimeException(e);
> В случае такой обработки ошибок лучше использовать аннотацию @SneakyThrows

Исправлено.

2023-02-06 15:31 UTC, SerhiiTrehubenko commented on goods-partner-backend/src/main/java/com/goodspartner/entity/SettingsExternal.java
> +    public static class GroupId implements Serializable {
> что будет если убрать Serializable?

Так как класс SettingsExternal хранится в базе, значит от должен быть сериализован (для возможности транспортировки через O/I streams), в то же время,  мы используем GroupId как композитный ключ, соответсвенно   его пропертя будут использованы в базе как примари кей, как результат он тоже подлежин сериализации.

2023-02-06 15:31 UTC, SerhiiTrehubenko commented on goods-partner-backend/src/main/java/com/goodspartner/cache/DefaultSettingsCache.java
> +    private static Map<String, Map<String, SettingsExternal>> settingsCache;
> Статика - сразу реджект. Зачем он статический? Убрать.

Исправлено.

2023-02-06 15:32 UTC, SerhiiTrehubenko commented on goods-partner-backend/src/main/java/com/goodspartner/cache/DefaultSettingsCache.java
> +        isEmptyMap();
> I dont understand purpose of this method

Исправлено.

2023-02-11 01:24 UTC, belosh59 approved these changes

2023-02-11 06:38 UTC, Rooman approved these changes

2023-02-11 09:51 UTC, merged