Resync orders.
GoodsPartner/GoodsPartner pull request #611
Opened 2023-04-06 17:07 UTC by 0ffffh

Remove redundant orders, and do not touch the rescheduled one

2023-04-06 22:16 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/facade/impl/DefaultDeliveryFacade.java
> +            throw new IllegalDeliveryStateForRecalculation();
Why you remove orders in two lines above if you suppose to throw exception just next line later

2023-04-06 22:21 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/repository/OrderExternalRepository.java
> +    @EntityGraph(attributePaths = {"delivery"})
EntityGraph ? What is the purpose here?

2023-04-06 22:25 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/facade/impl/DefaultDeliveryFacade.java
> +        Delivery delivery = deliveryService.findByIdWithOrders(deliveryId);
why do we need specifically withOrders?

2023-04-06 22:30 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultDeliveryService.java
> +
Not sure why we need it

2023-04-06 23:05 UTC, belosh59 requested changes

2023-04-07 08:59 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/facade/impl/DefaultDeliveryFacade.java
> +            throw new IllegalDeliveryStateForRecalculation();
fixed

2023-04-07 08:59 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/repository/OrderExternalRepository.java
> +    @EntityGraph(attributePaths = {"delivery"})
fixed

2023-04-07 08:59 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/facade/impl/DefaultDeliveryFacade.java
> +        Delivery delivery = deliveryService.findByIdWithOrders(deliveryId);
fixed

2023-04-07 08:59 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/service/impl/DefaultDeliveryService.java
> +
fixed

2023-04-07 08:59 UTC, 0ffffh commented on goods-partner-backend/src/main/java/com/goodspartner/web/controller/DeliveryController.java
> +    @PreAuthorize("hasRole('ADMIN')")
fixed

2023-04-07 09:20 UTC, 0ffffh commented on goods-partner-backend/src/test/resources/dbunit.yml
> +  allowEmptyFields: true
this option allow dbrider to call insert with empty strings. In test dataset I have some null values

2023-04-08 10:02 UTC, belosh59 approved these changes

2023-04-08 21:18 UTC, merged