Throw exception if no necessary 1C data
GoodsPartner/GoodsPartner pull request #844
Opened 2023-06-03 06:47 UTC by TarasOrlovskyi

2023-06-03 22:47 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/dto/external/grandedolce/ODataInvoiceDto.java
> +        value = getCheckedMapStringValue(value, "Контрагент", DOCUMENT_NAME, number);
Better to not reset initial value.
I would propose to have void methods in ODataUtil, this way you would even be able to simplify it with wildcard ?

2023-06-03 22:49 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/util/ODataUtils.java
> +    }
Proposal is to make the methods return void but accept wildcard map
```
public static void throwIfNull(Map<String, ?> value, String field, String documentName, String documentNumber) {
```

2023-06-03 22:52 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/dto/external/grandedolce/ODataInvoiceDto.java
> +        value = getCheckedMapStringValue(value, "Организация", DOCUMENT_NAME, number);
If you would implement below the usage become:
```
    @JsonProperty("Организация")
    private void mapCompanyName(Map<String, String> value) {
//        value = getCheckedMapStringValue(value, "Организация", DOCUMENT_NAME, number);
        throwIfNull(value, "Организация", DOCUMENT_NAME, number);
        this.companyName = value.get("НаименованиеПолное");
    }
```

2023-06-03 22:54 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/dto/external/grandedolce/ODataInvoiceDto.java
> +    private static final String DOCUMENT_NAME = "Document_РеализацияТоваровУслуг";
Not sure if it would be convenient to read details with prefix `Document_`
I think simple `РеализацияТоваровУслуг` would go laconically

2023-06-03 22:55 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/dto/external/grandedolce/ODataInvoiceProductDto.java
> +        Map<String, Object> productUnit = getCheckedMapObjectValue((Map<String, Object>) value.get("ЕдиницаХраненияОстатков"), "ЕдиницаХраненияОстатков", DOCUMENT_NAME, refKey);
make sense to get those parts as `ЕдиницаХраненияОстатков` to class constants

2023-06-03 22:57 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/dto/external/grandedolce/ODataInvoiceProductDto.java
> +        value = getCheckedMapStringValue(value, "ЕдиницаИзмерения", DOCUMENT_NAME, refKey);
I have filling that even annotation string should go well with static class constants 
Try to extract it to common place and reuse in both

2023-06-03 22:57 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/dto/external/grandedolce/ODataInvoiceProductDto.java
> +    private static final String DOCUMENT_NAME = "Document_РеализацияТоваровУслуг_Товары";
Document_ here as well

2023-06-03 22:58 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/service/dto/external/grandedolce/ODataProductDto.java
> +    private static final String DOCUMENT_NAME = "Document_ЗаказПокупателя_Товары";
Also here, and in other places not sure that prefix` Document_` is meaningfull for Admin or Logist

2023-06-03 23:01 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/exception/MissedField1CException.java
> +        super(message);
Lets move message translation under exception as we do in other places.
This would also simplify your code sice you could define specific constructor with params for document and its filed

2023-06-03 23:17 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/web/handler/DocumentControllerAdvice.java
> +        ErrorResponse errorResponse = new ErrorResponse(HttpStatus.BAD_GATEWAY, exception.getMessage());
BAD_GATEWAY

2023-06-03 23:19 UTC, Rooman requested changes
Tests please

2023-06-04 09:11 UTC, TarasOrlovskyi commented on goods-partner-backend/src/main/java/com/goodspartner/web/handler/DocumentControllerAdvice.java
> +        ErrorResponse errorResponse = new ErrorResponse(HttpStatus.BAD_GATEWAY, exception.getMessage());
Why not?

2023-06-04 15:39 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/web/handler/DocumentControllerAdvice.java
> +        ErrorResponse errorResponse = new ErrorResponse(HttpStatus.BAD_GATEWAY, exception.getMessage());
what BAD_GATEWAY means?

2023-06-04 15:40 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/web/handler/DocumentControllerAdvice.java
> +        ErrorResponse errorResponse = new ErrorResponse(HttpStatus.BAD_GATEWAY, exception.getMessage());
Please change it to InternalServerError, this would be enough

2023-06-04 15:40 UTC, Rooman commented on goods-partner-backend/src/main/java/com/goodspartner/web/handler/DocumentControllerAdvice.java
> +        ErrorResponse errorResponse = new ErrorResponse(HttpStatus.BAD_GATEWAY, exception.getMessage());
Status code 418 will be more useful I think

2023-06-04 17:45 UTC, TarasOrlovskyi commented on goods-partner-backend/src/main/java/com/goodspartner/web/handler/DocumentControllerAdvice.java
> +        ErrorResponse errorResponse = new ErrorResponse(HttpStatus.BAD_GATEWAY, exception.getMessage());
A 502 bad gateway message indicates that one server got an invalid response from another. It seems to me that this case is about that. But, ok. As you wish I will set 418

2023-06-04 18:29 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/web/handler/DocumentControllerAdvice.java
> +        return ResponseEntity.status(HttpStatus.I_AM_A_TEAPOT).body(errorResponse);
:)

2023-06-04 18:39 UTC, belosh59 commented on goods-partner-backend/src/main/java/com/goodspartner/web/handler/DocumentControllerAdvice.java
> +        return ResponseEntity.status(HttpStatus.I_AM_A_TEAPOT).body(errorResponse);
Sometimes it could be funny, but I still do like if we go with simple InternalServerError and thats its.
@TarasOrlovskyi @Rooman  guys lets not complicate it, neither make fun of it

2023-06-04 20:09 UTC, belosh59 approved these changes

2023-06-04 20:11 UTC, Rooman submitted a review, later dismissed

2023-06-17 16:06 UTC, belosh59 approved these changes

2023-06-17 16:58 UTC, merged