Added mocking data logic plus tests
GoodsPartner/GoodsPartner pull request #956
Opened 2023-07-05 22:32 UTC by TarasOrlovskyi

2023-07-07 00:28 UTC, Rooman requested changes
should not go into develop

2023-07-10 00:20 UTC, belosh59 approved these changes

2023-07-13 11:15 UTC, Rooman approved these changes

2023-07-13 11:23 UTC, belosh59 approved these changes

2023-07-13 11:34 UTC, merged